use role sysadmin;
-- CREATE OR REPLACE TABLE ROOT_DEPTH(
--     ROOT_DEPTH_ID number(1),
--     ROOT_DEPTH_CODE text(1),
--     ROOT_DEPTH_NAME text(7),
--     UNIT_OF_MEASURE text(2),
--     RANGE_MIN number(2),
--     RANGE_MAX number(2)
-- );

show tables;
DESC TABLE ROOT_DEPTH; -- DESCRIBE THE TABLE

-- INSERTING
use warehouse COMPUTE_WH;

insert into ROOT_DEPTH (ROOT_DEPTH_ID,ROOT_DEPTH_CODE,ROOT_DEPTH_NAME,UNIT_OF_MEASURE,RANGE_MIN,RANGE_MAX) values
(1,'S','Shallow','cm',30,45);

insert into ROOT_DEPTH (ROOT_DEPTH_ID,ROOT_DEPTH_CODE,ROOT_DEPTH_NAME,UNIT_OF_MEASURE,RANGE_MIN,RANGE_MAX) values
(2,'M','Medium','cm',45,60),(3,'D','Deep','cm',60,90);

SELECT * FROM ROOT_DEPTH; -- (SELECT * FROM GARDEN_PLANTS.VEGGIES.ROOT_DEPTH; -> DATABASE_NAME.SCHEMA_NAME.TABLE_NAME)

SELECT * FROM ROOT_DEPTH LIMIT 1;

 SELECT TOP 1 * FROM GARDEN_PLANTS.VEGGIES.ROOT_DEPTH; -- SQL Server / MS Access Syntax:TOP <=> LIMIT